#!/bin/bash

# This script will call the two scripts required to perform the analyses. _bl_download.sh_ downloads the needed summary statistics files (.csv) from brainlife.io.
# _analyzeGmWmData.py_ will perform all the analyses found in Kay et al, in Prep.

# set top directory. this is the filepath you want the data to be downloaded into, and the analyses to be completed in. This path should be added to the config.json file in the 'topPath' variable. This directory does not have to be created before running and will be created in bl_download.sh.
topDir=`jq -r '.topPath' config.json`

# download data
. bl_download.sh $topDir

# analyze group data (if singularity)
time singularity exec -e docker://bacaron/athlete-brain-container:v1.0 ./analyzeGmWmData.py
